### ISSUE TITLE
modules 를 못찾는다는 Error가 계속 뜹니다.

### ISSUE THREAD

**Issue by seungjohan** [Joon-na-Seriously/seungjohan-node-react-basic#1]
modules 를 못찾는다는 Error가 계속 뜹니다.
그래서 프론트랑 연결해서 체크해보려고 해도 되지가 않습니다.
models/User

user 잘 import되는지 코드랑으로 전부 확인해봤는데 잘안되네요

-------------

> boilder-plate@1.0.0 backend /Users/seungjohan/PycharmProjects/nodereact-basic/boilder-plate
> nodemon server/index.js

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/index.js`
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './models/User'
Require stack:
- /Users/seungjohan/PycharmProjects/nodereact-basic/boilder-plate/server/middleware/auth.js
- /Users/seungjohan/PycharmProjects/nodereact-basic/boilder-plate/server/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/seungjohan/PycharmProjects/nodereact-basic/boilder-plate/server/middleware/auth.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/seungjohan/PycharmProjects/nodereact-basic/boilder-plate/server/index.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/seungjohan/PycharmProjects/nodereact-basic/boilder-plate/server/middleware/auth.js',
    '/Users/seungjohan/PycharmProjects/nodereact-basic/boilder-plate/server/index.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by seungjohan** [comment]
https://www.inflearn.com/questions/29959

공용와이파이는 가끔씩 안되는 경우가 있다고 한다.
나도 모르겠다.....

각자 집에서 코딩하자....
